name: Syncronize
on:
  workflow_dispatch:
  schedule:
    #          2 4  10 12 18 20 -7
    - cron: 20 19,21,3,5,11,13 * * *
  # - cron: '30 3,5,11,13,19,21 * * *'
  # - cron: '*/6 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.0
      - name: Install Dependencies
        run: npm i
      - name: Running
        run: node exe.js
